name: Weekly OWID COVID-19 Data Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write  # Ensure the workflow has write permissions

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate comparison

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run data update script
        run: python scripts/update_data.py

      - name: Check for Changes
        id: changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "##[set-output name=changes_detected;]false"
          else
            echo "##[set-output name=changes_detected;]true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/owid-covid-data.csv
          git commit -m "Automated weekly data update"
          git push

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'COVID Data Update Failed',
              body: `The automated data update workflow failed at ${new Date().toISOString()}. Please check the workflow logs.`,
              labels: ['automation-failure', 'bug']
            })

      - name: Create Issue on Success
        if: success() && steps.changes.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'COVID Data Updated Successfully',
              body: `Data update completed successfully at ${new Date().toISOString()}.`,
              labels: ['automation-success']
            })
