name: Weekly OWID COVID-19 Data Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run data update script
        run: python scripts/update_data.py

      - name: Commit and push changes
        if: success()  # Only run this step if previous steps succeeded
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/owid-covid-data.csv
          git commit -m "Automated weekly data update" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

      - name: Create Issue on Failure
        if: failure()  # Only run this step if a previous step fails
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'COVID Data Update Failed',
              body: `The automated data update workflow failed at ${new Date().toISOString()}. Please check the workflow logs.`,
              labels: ['automation-failure', 'bug']
            })

      - name: Create Issue on Success
        if: success()  # Only run this step if all steps succeeded
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'COVID Data Updated Successfully',
              body: `Data update completed successfully at ${new Date().toISOString()}.`,
              labels: ['automation-success']
            })
