name: Weekly OWID COVID-19 Data Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Data Update Script
        run: python scripts/update_data.py

      - name: Check for Changes
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.changes_detected == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/owid-covid-data.csv
          git commit -m "Automated data update for $(date +'%B %Y')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No Changes Detected
        if: env.changes_detected == 'false'
        run: echo "No changes to commit. Skipping the commit and push steps."
